### PR TITLE
Use `fmt.Fprintf`

### PR DESCRIPTION
**Pull request by cristaloleg**
Hey, thanks for the tool. Made a small PR which simplifies few printing things.

### CODE REVIEW

**Comment by cristaloleg** [comment]
Looks like a problem with UI is not my fault.

**Comment by Zxilly** [comment]
Thanks for your contribution, but I may have to fix the CI first.

**Comment by Zxilly** [comment]
Could you please try to rebase onto the master branch and then check if the CI is working properly?

**Review by Zxilly — APPROVED** [review]
lgtm

**Comment by Zxilly** [comment]
Thanks for your contribution.

**Pull request merged**
