### PR TITLE
github actions typos

### PR DESCRIPTION
**Pull request by ccoVeille**
- **ci: GitHub actions to detect typos #32**
- **chore: fix obvious typos in code**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I have no idea what a pres-udo could be :sweat_smile: 

https://github.com/Zxilly/go-size-analyzer/blob/e1be139c8ffac238b715be446324480ed6806672/internal/dependencies.go#L12

**Comment by Zxilly** [comment]
it should be pseudo

**Comment by ccoVeille** [comment]
> it should be pseudo

OK, I pushed it back with a fix

**Review by Zxilly — APPROVED** [review]
lgtm

**Pull request merged**
